apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-test
  labels:
    app: my-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-test
  template:
    metadata:
      labels:
        app: my-app-test
    spec:
      containers:
      - name: simple-node-test
        image: jempitman/simple-node-test
        ports:
        - containerPort: 8080